name: Pritesh Shrivastava's blog
url: http://pritesh-shrivastava.github.io
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: jekyll-theme-hacker