name: Pritesh Shrivastava's blog
url: http://pritesh-shrivastava.github.io
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-hacker
markdown: kramdown
future: false
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
#        css_class: 'highlight'
